// APP
export const CHANGE_PAGE = 'CHANGE_PAGE'

// Cart
export const CART_ADD_ITEM = 'CART_ADD_ITEM'
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM'
export const CART_CHANGE_ITEM_AMOUNT = 'CART_CHANGE_ITEM_AMOUNT'
export const CART_CALCULATE = 'CART_CALCULATE'
export const CART_CHECKOUT = 'CART_CHECKOUT'