// APP
export const APP_LOGIN = 'APP_LOGIN'
export const APP_LOGOUT = 'APP_LOGOUT'
export const PRODUCT_LIST = 'PRODUCT_LIST'

// Cart
export const CART_ADD_ITEM = 'CART_ADD_ITEM'
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM'
export const CART_CHANGE_ITEM_AMOUNT = 'CART_CHANGE_ITEM_AMOUNT'
export const CART_CALCULATE = 'CART_CALCULATE'
export const CART_CHECKOUT = 'CART_CHECKOUT'
export const CART_CLEAR = 'CART_CLEAR'